-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 15, 2025 at 03:12 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `webbanhang_cnpm`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_sanpham`
--

CREATE TABLE `tbl_sanpham` (
  `id_sp` int(11) NOT NULL,
  `ten_sp` varchar(200) NOT NULL,
  `ma_sp` varchar(100) NOT NULL,
  `gia_sp` int(11) NOT NULL,
  `so_luong` int(11) NOT NULL,
  `so_luong_con_lai` int(11) NOT NULL,
  `hinh_anh` varchar(50) NOT NULL COMMENT 'Ảnh chính',
  `hinh_anh_2` varchar(50) DEFAULT NULL COMMENT 'Ảnh phụ 1',
  `hinh_anh_3` varchar(50) DEFAULT NULL COMMENT 'Ảnh phụ 2',
  `tom_tat` text DEFAULT NULL,
  `noi_dung` longtext DEFAULT NULL,
  `id_dm` int(11) NOT NULL,
  `tinh_trang` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tbl_sanpham`
--

INSERT INTO `tbl_sanpham` (`id_sp`, `ten_sp`, `ma_sp`, `gia_sp`, `so_luong`, `so_luong_con_lai`, `hinh_anh`, `tom_tat`, `noi_dung`, `id_dm`, `tinh_trang`) VALUES
(140, 'Áo Sân Nhà Manchester City 2023 2024', 'MCIH2324', 350000, 100, 100, 'mci2324.png', 'Áo Manchester City Sân Nhà Mùa 2023/24\\r\\n\\r\\nKỷ niệm 20 năm tại sân Etihad, áo Manchester City mùa 2023/24 được thiết kế với họa tiết nổi bật từ sân Etihad và vích cổ trắng. Áo sử dụng chất liệu dryCELL thoáng mát và có logo câu lạc bộ cùng logo PUMA. Mua áo chính thức để nhận được chất lượng cao và đóng góp cho chương trình từ thiện City in the Community.', 'Dưới đây là nội dung được chỉnh sửa để loại bỏ các ký tự không cần thiết và đảm bảo dễ đọc hơn:\\r\\n\\r\\nÁo Manchester City Sân Nhà Mùa 2023/24\\r\\nChúng tôi kỷ niệm 20 năm Manchester City tại sân Etihad với áo sân nhà mùa 2023/24. Áo này được thiết kế nhằm tôn vinh các chi tiết nổi bật của sân và gợi nhớ đến áo sân đầu tiên được mặc trong mùa giải đầu tiên tại Etihad.\\r\\n\\r\\nĐặc điểm nổi bật:\\r\\nHọa tiết trên áo: Áo được trang trí với các họa tiết tôn lên kiến trúc đặc trưng của sân Etihad, bao gồm các khối tượng lớn bên ngoài sân.\\r\\nViền cổ: Viền cổ trắng, lấy cảm hứng từ thiết kế áo sân mùa giải đầu tiên tại Etihad.\\r\\nLogo: Logo câu lạc bộ và logo PUMA Cat được đặt trên ngực và cả hai tay áo.\\r\\nChất liệu: Sử dụng công nghệ dryCELL, giúp thấm hút mồ hôi và giữ cơ thể luôn mát mẻ trong suốt quá trình tập luyện.\\r\\nNội dung in: Chữ \\\"CITY\\\" được khắc ở cổ tay sau, kèm theo hình ảnh sân Etihad in bên trong cổ áo.\\r\\nLý do mua:\\r\\nKỷ niệm đặc biệt: Đánh dấu 20 năm Manchester City thi đấu tại sân Etihad.\\r\\nChất lượng cao: Áo chính thức, được thiết kế với công nghệ hiện đại và độ bền cao.\\r\\nĐóng góp xã hội: Mỗi chiếc áo bán ra sẽ đóng góp £5 cho chương trình City in the Community, hỗ trợ cải thiện cuộc sống của thanh niên thông qua bóng đá.', 65, 1),
(141, 'Áo Sân Khách Manchester City 2023 2024', 'MCIA2324', 350000, 100, 100, 'mcia2324.jpg', 'Áo Manchester City Sân Khách Mùa 2023/24\\r\\n\\r\\nThiết kế độc đáo và phong cách với màu sắc và họa tiết mới mẻ. Áo sử dụng công nghệ dryCELL tiên tiến, thấm hút mồ hôi và giữ cơ thể khô ráo. Logo câu lạc bộ và logo PUMA đảm bảo chất lượng và tính xác thực. Phù hợp cho cả việc cổ vũ đội bóng và sử dụng hàng ngày.', 'Dưới đây là nội dung đã được chỉnh sửa để loại bỏ các ký tự không cần thiết và đảm bảo dễ đọc hơn:\\r\\n\\r\\nÁo Manchester City Sân Khách Mùa 2023/24\\r\\nKhám phá sự độc đáo và phong cách với áo Manchester City sân khách mùa 2023/24. Áo này không chỉ thể hiện tình yêu và sự ủng hộ cho đội bóng mà còn mang đến sự thoải mái và thời trang đỉnh cao.\\r\\n\\r\\nĐặc điểm nổi bật:\\r\\nThiết kế: Áo có màu sắc và họa tiết đặc biệt, khác biệt hoàn toàn so với áo sân nhà, mang lại vẻ ngoài mới mẻ và hiện đại.\\r\\nChất liệu: Sử dụng công nghệ dryCELL tiên tiến, giúp thấm hút mồ hôi và giữ cơ thể luôn khô ráo.\\r\\nLogo: Trang bị logo câu lạc bộ và logo PUMA Cat trên ngực và tay áo, đảm bảo chất lượng và tính xác thực.\\r\\nCổ áo và tay áo: Thiết kế tinh tế, tạo điểm nhấn phong cách và hiện đại.\\r\\nLý do mua:\\r\\nPhong cách độc đáo: Áo sân khách mang lại vẻ ngoài khác biệt, vừa thời trang vừa phù hợp cho việc cổ vũ đội bóng hoặc sử dụng hàng ngày.\\r\\nChất lượng vượt trội: Sản phẩm chính hãng, được sản xuất bởi PUMA với chất lượng đảm bảo.\\r\\nTiện ích và thoải mái: Thiết kế và chất liệu đảm bảo sự thoải mái trong mọi hoạt động.', 65, 1),
(142, 'Áo Thứ Ba Manchester City 2023 2024', 'MCIT2324', 350000, 100, 99, 'mcit2324.jpg', 'Áo Thứ Ba Manchester City Mùa 2023/24\\r\\n\\r\\nThiết kế độc đáo và phong cách với màu sắc và họa tiết mới mẻ. Áo sử dụng công nghệ dryCELL tiên tiến, thấm hút mồ hôi và giữ cơ thể khô ráo. Logo câu lạc bộ và logo PUMA đảm bảo chất lượng và tính xác thực. Phù hợp cho cả việc cổ vũ đội bóng và sử dụng hàng ngày.', 'Áo Thứ Ba Manchester City Mùa 2023/24\\r\\n\\r\\nKhám phá sự độc đáo và phong cách với áo thứ ba Manchester City mùa 2023/24. Áo này không chỉ thể hiện tình yêu và sự ủng hộ cho đội bóng mà còn mang đến sự thoải mái và thời trang đỉnh cao.\\r\\n\\r\\nĐặc điểm nổi bật:\\r\\nThiết kế: Áo có màu sắc và họa tiết đặc biệt, khác biệt so với áo sân nhà và áo sân khách, mang lại vẻ ngoài mới mẻ và hiện đại.\\r\\nChất liệu: Sử dụng công nghệ dryCELL tiên tiến, giúp thấm hút mồ hôi và giữ cơ thể luôn khô ráo.\\r\\nLogo: Được trang bị logo câu lạc bộ và logo PUMA Cat trên ngực và tay áo, đảm bảo chất lượng và tính xác thực.\\r\\nCổ áo và tay áo: Thiết kế tinh tế, tạo điểm nhấn phong cách.\\r\\nLý do mua:\\r\\nPhong cách độc đáo: Áo thứ ba mang lại vẻ ngoài khác biệt, phù hợp cả khi cổ vũ đội bóng lẫn sử dụng hàng ngày.\\r\\nChất lượng vượt trội: Sản phẩm chính hãng, đảm bảo chất lượng từ PUMA và Manchester City.\\r\\nTiện ích và thoải mái: Chất liệu và thiết kế mang đến sự thoải mái trong mọi hoạt động.', 65, 1),
(143, 'Áo Sân Nhà Liverpool mùa 2024 2025', 'LIVH2425', 350000, 100, 100, 'LIVH2324.jpg', 'Áo Sân Nhà Liverpool Mùa 2024/25\\r\\n\\r\\nThiết kế độc đáo và phong cách với màu sắc và họa tiết mới mẻ. Áo sử dụng công nghệ Dri-Fit ADV tiên tiến, thấm hút mồ hôi và giữ cơ thể khô ráo. Logo câu lạc bộ và logo Nike đảm bảo chất lượng và tính xác thực. Phù hợp cho cả việc cổ vũ đội bóng và sử dụng hàng ngày.', 'Áo Sân Nhà Liverpool Mùa 2024/25\\r\\nKhám phá sự độc đáo và phong cách với áo sân nhà Liverpool mùa 2024/25. Áo này không chỉ thể hiện tình yêu và sự ủng hộ cho đội bóng mà còn mang đến sự thoải mái và thời trang đỉnh cao.\\r\\n\\r\\nĐặc điểm nổi bật:\\r\\nThiết kế: Áo có màu sắc và họa tiết đặc biệt, mang lại vẻ ngoài mới mẻ và hiện đại.\\r\\nChất liệu: Sử dụng công nghệ Dri-Fit ADV tiên tiến, giúp thấm hút mồ hôi và giữ cơ thể luôn khô ráo.\\r\\nLogo: Được trang bị logo câu lạc bộ và logo Nike trên ngực và tay áo, đảm bảo chất lượng và tính xác thực.\\r\\nCổ áo và tay áo: Thiết kế tinh tế, tạo điểm nhấn phong cách.\\r\\nLý do mua:\\r\\nPhong cách độc đáo: Áo sân nhà mang lại vẻ ngoài khác biệt, phù hợp cả khi cổ vũ đội bóng lẫn sử dụng hàng ngày.\\r\\nChất lượng vượt trội: Sản phẩm chính hãng, đảm bảo chất lượng từ Nike và Liverpool.\\r\\nTiện ích và thoải mái: Chất liệu và thiết kế mang đến sự thoải mái trong mọi hoạt động.', 65, 1),
(144, 'Áo Sân Nhà Chelsea 2024 2025', 'CHEH2425', 350000, 100, 100, 'CHEH2425.jpg', 'Áo Sân Nhà Chelsea Mùa 2024/25\\r\\n\\r\\nThiết kế độc đáo và phong cách với màu sắc và họa tiết mới mẻ. Áo sử dụng công nghệ AeroSwift tiên tiến, thấm hút mồ hôi và giữ cơ thể khô ráo. Logo câu lạc bộ và logo Nike đảm bảo chất lượng và tính xác thực. Phù hợp cho cả việc cổ vũ đội bóng và sử dụng hàng ngày.', 'Áo Sân Nhà Chelsea Mùa 2024/25\\r\\n\\r\\nHòa nhịp cùng niềm đam mê và phong cách với áo sân nhà Chelsea mùa 2024/25. Áo này không chỉ thể hiện tình yêu và sự ủng hộ mãnh liệt cho đội bóng mà còn mang đến sự thoải mái và thời trang đỉnh cao.\\r\\n\\r\\nĐặc điểm nổi bật:\\r\\n\\r\\nThiết kế: Áo có thiết kế màu xanh truyền thống của Chelsea, kết hợp với các chi tiết và họa tiết hiện đại, tạo nên vẻ ngoài mới mẻ và thu hút.\\r\\nChất liệu: Sử dụng công nghệ AeroSwift tiên tiến, giúp thấm hút mồ hôi và giữ cơ thể luôn khô ráo, thoải mái suốt cả ngày.\\r\\nLogo: Được trang bị logo câu lạc bộ Chelsea và logo Nike trên ngực và tay áo, đảm bảo chất lượng và tính xác thực.\\r\\nCổ áo và tay áo: Thiết kế cổ áo và tay áo tạo điểm nhấn tinh tế và phong cách độc đáo.\\r\\nLý do mua:\\r\\n\\r\\nPhong cách đậm chất Chelsea: Áo sân nhà mang lại vẻ ngoài thể thao và thời trang, phù hợp cho cả việc cổ vũ đội bóng và sử dụng hàng ngày.\\r\\nChất lượng vượt trội: Sản phẩm chính hãng, đảm bảo chất lượng từ Nike và Chelsea.\\r\\nTiện ích và thoải mái: Chất liệu và thiết kế đảm bảo sự thoải mái trong mọi hoạt động, từ cổ vũ trên sân vận động đến các hoạt động thể thao hàng ngày.', 65, 1),
(150, 'Áo Sân Nhà Manchester United 2024 2025', 'MNUH2425', 350000, 200, 199, 'MNUH2425.png', 'Áo đấu nhà Manchester United mùa 2024-2025 được thiết kế bởi adidas và ra mắt vào ngày 1 tháng 7 năm 2024. Thiết kế áo này tạo ấn tượng mạnh mẽ với sự kết hợp của hai màu đỏ, từ đỏ nhạt đến đỏ sẫm, tạo hiệu ứng ánh sáng độc đáo khi ánh sáng Old Trafford chiếu lên. Áo đấu này có thêm một khối màu đỏ rực rỡ trên tay áo và quần, tạo thành một đường kết nối đặc biệt.', 'Thiết kế và màu sắc:\\n\\nMàu chính: Áo đấu có hai màu đỏ, từ đỏ nhạt đến đỏ sẫm, tạo hiệu ứng ánh sáng độc đáo.\\n\\nKhối đỏ rực rỡ: Một khối màu đỏ rực rỡ trên tay áo và quần, tạo thành một đường kết nối đặc biệt.\\n\\nCổ áo: Áo có cổ áo crew neck và logo adidas ba dòng trên vai.\\n\\nLogo và đối tác chính: Logo của đối tác chính Snapdragon và logo adidas đều có màu trắng tạo sự tương phản.\\n\\nChất liệu và công nghệ:\\n\\nChất liệu: Áo đấu được làm từ vật liệu tái chế, giúp giảm thiểu rác thải và tài nguyên hạn chế.\\n\\nCông nghệ: Áo đấu có công nghệ HEAT.RDY giúp tối ưu hóa luồng mây để giữ cơ thể cảm thấy mát mẻ, và công nghệ AEROREADY giúp bớt mồ hôi và giữ cơ thể khô ráo', 65, 1),
(151, 'Áo Sân Nhà Manchester City 2024 2025', 'MCIH2425', 350000, 150, 149, 'MCIH2425.jpg', 'Áo đấu nhà Manchester City mùa 2024-2025 được thiết kế bởi PUMA và ra mắt vào ngày 16 tháng 5 năm 2024. Thiết kế áo này tạo ấn tượng mạnh mẽ với màu xanh dương bầu trời, kết hợp với các sợi chỉ \\\"0161\\\" trên tay áo và cổ tay, đại diện cho mã số điện thoại của Manchester. Áo đấu này không chỉ tạo sự tương phản mà còn thể hiện sự tự hào Citizens', 'Thiết kế và màu sắc:\\n\\nMàu chính: Áo đấu có màu xanh dương bầu trời, tạo sự tương phản với các sợi chỉ \\\"0161\\\" trên tay áo và cổ tay.\\n\\nSợi chỉ \\\"0161\\\": Sự kết hợp của mã số điện thoại của Manchester, tạo ra sự đặc biệt và gắn kết với cội nguồn Mancunian.\\n\\nCổ áo: Áo có cổ áo crew neck và logo PUMA ba dòng trên vai.\\n\\nLogo và đối tác chính: Logo của đối tác chính và logo PUMA đều có màu trắng tạo sự tương phản.\\n\\nChất liệu và công nghệ:\\n\\nChất liệu: Áo đấu được làm từ vật liệu tái chế, giúp giảm thiểu rác thải và tài nguyên hạn chế.\\n\\nCông nghệ: Áo đấu có công nghệ dry-CELL giúp bớt mồ hôi và giữ cơ thể khô ráo, và công nghệ RE:FIBRE giúp giảm trọng lượng và ma sát, tối ưu hóa hiệu suất cao cấp', 65, 1),
(152, 'Áo Sân Nhà Barcelona 2024 2025', 'BARH2425', 300000, 150, 150, 'BARH2425.jpg', 'Áo đấu nhà FC Barcelona mùa 2024-2025 được thiết kế bởi Nike và ra mắt vào ngày 18 tháng 7 năm 2024. Thiết kế áo này tạo ấn tượng mạnh mẽ với các sọc đỏ và xanh dương truyền thống, nhưng với một chút biến đổi hiện đại. Áo đấu này không chỉ thể hiện sự tự hào về lịch sử của câu lạc bộ mà còn mang đến sự độc đáo và đặc biệt.', 'Thiết kế và màu sắc:\\n\\nMàu chính: Áo đấu có các sọc đỏ và xanh dương truyền thống, nhưng với hiệu ứng biến đổi từ màu đỏ sang xanh dương tại phần giữa áo, tạo ra một vẻ đẹp độc đáo.\\n\\nCổ áo: Áo có cổ áo crew neck và logo Nike ba dòng trên vai.\\n\\nLogo và đối tác chính: Logo của đối tác chính và logo Nike đều có màu vàng, tạo sự tương phản với các sọc đỏ và xanh dương.\\n\\nChất liệu và công nghệ:\\n\\nChất liệu: Áo đấu được làm từ vật liệu tái chế, giúp giảm thiểu rác thải và tài nguyên hạn chế.\\n\\nCông nghệ: Áo đấu có công nghệ Dri-FIT giúp bớt mồ hôi và giữ cơ thể khô ráo, và công nghệ RE:FIBRE giúp giảm trọng lượng và ma sát, tối ưu hóa hiệu suất cao cấp.', 65, 1),
(153, 'Áo Sân Khách Barcelona 2024 2025', 'BARA2425', 350000, 175, 174, 'BARA2425.jpg', 'Áo đấu sân khách của FC Barcelona cho mùa 2024-2025 là một sự kỷ niệm đặc biệt đến 125 năm lịch sử của câu lạc bộ. Thiết kế áo này được lấy cảm hứng từ trang phục đầu tiên của Barça vào năm 1899, với màu sắc chính là đen. Áo đấu này không chỉ thể hiện sự đặc biệt và độc đáo mà còn mang lại sự tôn vinh cho nguồn gốc của câu lạc bộ.', 'Thiết kế: Áo đấu sân khách của mùa 2024-2025 có thiết kế đặc biệt với màu đen chính và các dải xanh và đỏ tạo thành vòng tròn trên nền đen, tạo ra sự tương phản mạnh mẽ và ấn tượng. Biểu tượng của Barça được in trên áo với màu đen, được bao quanh bởi các màu xanh và đỏ2.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ Dri-FIT ADV của Nike, cung cấp độ thoải mái, thở dễ dàng và giữ ấm tốt nhất cho cơ thể người chơi.\\n\\nLogo: Áo đấu sẽ có logo Spotify trên phía trước, cùng với logo Nike, và logo Ambilight TV trên tay áo của đội tuyển nam. Đối với đội tuyển nữ, logo Bimbo sẽ xuất hiện trên tay áo3.\\n\\nSản phẩm: Áo đấu sẽ có sẵn từ tháng 9 năm 2024 và có thể được mua tại các cửa hàng Barça và trực tuyến.', 65, 1),
(154, 'Áo Sân Nhà Arsenal 2024 2025', 'ARSH2425', 250000, 120, 120, 'ARSH2425.png', 'Áo đấu sân nhà của Arsenal cho mùa giải 2024-2025 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là màu đỏ tươi, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự trẻ trung, năng động cho đội bóng.', 'Thiết kế: Áo đấu sân nhà của mùa giải 2024-2025 có màu đỏ tươi chủ đạo, kết hợp với các chi tiết màu trắng trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ Arsenal được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của Adidas, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo Emirates Fly Better ở phía trước, cùng với logo Adidas.', 65, 1),
(155, 'Áo Sân Nhà Manchester United 2023 2024', 'MNUH2324', 250000, 100, 100, 'MNUH2324.jpg', 'Áo đấu sân nhà của Manchester United cho mùa giải 2023-2024 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là màu đỏ tươi, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự trẻ trung, năng động cho đội bóng.', 'Thiết kế: Áo đấu sân nhà của mùa giải 2023-2024 có màu đỏ tươi chủ đạo, kết hợp với các chi tiết màu trắng trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ Manchester United được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của Adidas, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo Adidas trên phía trước, cùng với logo của câu lạc bộ.', 65, 1),
(156, 'Áo Sân Nhà Real Madrid 2024 2025', 'REAH2425', 299000, 100, 100, 'REAH2425.jpg', 'Áo đấu sân nhà của Real Madrid cho mùa giải 2024-2025 là một biểu tượng của sự thanh lịch và mạnh mẽ. Với màu trắng truyền thống, áo đấu mang đến cảm giác tinh tế nhưng vẫn không kém phần hiện đại. Thiết kế này tôn vinh lịch sử vĩ đại của câu lạc bộ, đồng thời truyền tải tinh thần đổi mới và năng động.', 'Thiết kế: Áo đấu sân nhà của mùa giải 2024-2025 có màu trắng chủ đạo, kết hợp với các chi tiết màu xanh dương và đỏ trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ Real Madrid được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của Adidas, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo Fly Emirates trên phía trước, cùng với logo Adidas.', 65, 1),
(157, 'Áo Sân Nhà AC Milan 2024 2025', 'ACMH2425', 349000, 190, 189, 'ACMH2425.jpg', 'Áo đấu sân nhà của AC Milan cho mùa giải 2024-2025 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là màu đỏ và đen, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự trẻ trung, năng động cho đội bóng.', 'Thiết kế: Áo đấu sân nhà của mùa giải 2024-2025 có thiết kế đặc biệt với các dải đỏ và đen truyền thống, kết hợp với các chi tiết màu trắng trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ AC Milan được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của Puma, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo Fly Emirates trên phía trước, cùng với logo Puma.', 65, 1),
(158, 'Áo Sân Nhà Inter Milan 2024 2025', 'INTH2425', 360000, 180, 180, 'INTH2425.jpg', 'Áo đấu sân nhà của Inter Milan cho mùa giải 2024-2025 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là màu xanh đen, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự trẻ trung, năng động cho đội bóng.', 'Thiết kế: Áo đấu sân nhà của mùa giải 2024-2025 có thiết kế đặc biệt với các dải xanh đen truyền thống, kết hợp với các chi tiết màu trắng trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ Inter Milan được in ở ngực trái, biểu tượng rắn Biscione đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của Nike, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo Betsson Sport trên phía trước, cùng với logo Nike.', 65, 1),
(159, 'Áo Sân Nhà Napoli 2024 2025', 'NAPH2425', 355000, 100, 100, 'NAPH2425.jpg', 'Áo đấu sân nhà của Napoli cho mùa giải 2024-2025 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là màu xanh dương Napoli, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự trẻ trung, năng động cho đội bóng.', 'Thiết kế: Áo đấu sân nhà của mùa giải 2024-2025 có thiết kế đặc biệt với các dải xanh dương truyền thống, kết hợp với các chi tiết màu trắng trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ Napoli được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của EA7, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo MSC trên phía trước, cùng với logo EA7.', 65, 1),
(160, 'Áo Sân Khách Napoli 2024 2025', 'NAPA2425', 299000, 100, 99, 'NAPA2425.jpg', 'Áo đấu sân khách của Napoli cho mùa giải 2024-2025 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là màu trắng, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự thanh lịch, tinh tế cho đội bóng.', 'Thiết kế: Áo đấu sân khách của mùa giải 2024-2025 có thiết kế đặc biệt với màu trắng chủ đạo, kết hợp với các chi tiết màu xanh dương và đỏ trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài thanh lịch nhưng không kém phần hiện đại. Logo của câu lạc bộ Napoli được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\n\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của EA7, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\n\\nLogo: Áo đấu sẽ có logo EA7 trên phía trước, cùng với logo của câu lạc bộ.', 65, 1),
(161, 'Áo Sân Nhà Bayern Munchen 2024 2025', 'BAYH2425', 350000, 180, 180, 'BAYH2425.jpg', 'Áo đấu sân nhà của Bayern Munich cho mùa giải 2024-2025 là một sự kết hợp hoàn hảo giữa truyền thống và hiện đại. Với thiết kế chủ đạo là ba màu đỏ khác nhau, áo đấu này không chỉ tôn vinh lịch sử lâu đời của câu lạc bộ mà còn mang lại sự động đậy và cảm xúc cho đội bóng.', '>Thiết kế: Áo đấu sân nhà của mùa giải 2024-2025 có thiết kế đặc biệt với ba màu đỏ khác nhau, kết hợp với các chi tiết màu trắng trên tay áo và cổ áo. Điều này tạo nên vẻ ngoài truyền thống nhưng không kém phần hiện đại. Logo của câu lạc bộ Bayern Munich được in ở ngực trái, biểu tượng pháo thủ đặc trưng của đội bóng.\\r\\n\\r\\nCông nghệ: Áo đấu được thiết kế với công nghệ tiên tiến của Adidas, giúp người chơi cảm thấy thoải mái, khô ráo và mát mẻ trong suốt quá trình thi đấu. Chất liệu vải nhẹ và thoáng khí, cùng với khả năng hút ẩm tốt, đảm bảo hiệu suất tối đa trên sân cỏ.\\r\\n\\r\\nLogo: Áo đấu sẽ có logo Allianz trên phía trước, cùng với logo Adidas.', 65, 1),
(162, 'Áo Sân Nhà Borrusia Dortmund 2024 2025', 'BVBH2425', 400000, 250, 249, 'BVBH2425.jpg', 'Áo đấu nhà mùa 2024-2025 của Borussia Dortmund mang thiết kế truyền thống và đầy thời hiện đại. Sản phẩm này có cổ tay đen và bốn sọc mỏng màu vàng trên áo. Phông chữ \\\"Dortmund\\\" đen rõ ràng trên lưng, cùng với khẩu hiệu \\\"Borussia verbindet\\\" (Borussia thống nhất) trên cổ tay. Áo đấu này được làm từ 95% polyester thải ra, góp phần bảo vệ môi trường.', 'Thiết kế: Áo đấu sân nhà mùa 2024-2025 của Borussia Dortmund mang đậm chất truyền thống với màu vàng chủ đạo. Cổ áo và cổ tay có màu đen tạo điểm nhấn tinh tế. Điểm đặc biệt là bốn sọc mỏng màu đen chạy dọc theo thân áo, tăng thêm tính thẩm mỹ và phong cách đặc trưng của đội bóng. Trên lưng áo có in chữ \\\"Dortmund\\\" màu đen rõ nét, cùng với khẩu hiệu \\\"Borussia verbindet\\\" (Borussia thống nhất) trên cổ tay, thể hiện tinh thần đoàn kết và gắn bó của câu lạc bộ.\\n\\nChất liệu: Áo đấu được làm từ 95% polyester tái chế, giúp bảo vệ môi trường và giảm thiểu rác thải. Chất liệu này không chỉ bền bỉ mà còn giúp thoáng khí, giữ cơ thể luôn khô ráo và thoải mái trong suốt quá trình vận động. Công nghệ dryCELL tích hợp trên áo giúp loại bỏ mồ hôi nhanh chóng, đảm bảo người mặc luôn cảm thấy thoải mái và tự tin.', 65, 1),
(163, 'Áo Sân Nhà Tottenham Hotspur 2024 2025', 'TOTH2425', 199000, 200, 199, 'TOTH2425.jpg', 'Áo đấu nhà mùa 2024-2025 của Tottenham Hotspur mang thiết kế truyền thống và hiện đại. Áo có màu trắng chủ đạo với cổ tay màu xanh dương, tạo sự tinh tế và đặc trưng cho đội bóng. Phông chữ \\\"Tottenham Hotspur\\\" màu đen rõ ràng trên lưng, cùng với khẩu hiệu \\\"To Dare Is To Do\\\" (Dũng cảm là hành động) trên cổ tay. Áo đấu này được làm từ 100% polyester tái chế, góp phần bảo vệ môi trường.', 'Thiết kế: Áo đấu nhà mùa 2024-2025 của Tottenham Hotspur có thiết kế truyền thống với màu trắng chủ đạo và cổ tay màu xanh dương. Phông chữ \\\"Tottenham Hotspur\\\" màu đen rõ ràng trên lưng, cùng với khẩu hiệu \\\"To Dare Is To Do\\\" (Dũng cảm là hành động) trên cổ tay.\\n\\nChất liệu: Áo đấu được làm từ 100% polyester tái chế, giúp bảo vệ môi trường và giảm thiểu rác thải. Chất liệu này không chỉ bền bỉ mà còn giúp thoáng khí, giữ cơ thể luôn khô ráo và thoải mái trong suốt quá trình vận động. Công nghệ Dri-FIT ADV tích hợp trên áo giúp loại bỏ mồ hôi nhanh chóng, đảm bảo người mặc luôn cảm thấy thoải mái và tự tin.', 65, 1),
(164, 'Áo Sân Nhà Newcastle United 2024 2025', 'NEWH2425', 300000, 150, 148, 'NEWH2425.jpg', 'Áo đấu nhà mùa 2024-2025 của Newcastle United mang thiết kế truyền thống và hiện đại. Áo có ba sọc đen rộng rãi trên thân áo, tạo điểm nhấn đặc trưng cho đội bóng. Phông chữ \\\"Newcastle United\\\" đen rõ ràng trên lưng, cùng với biểu tượng đội bóng trên cổ tay. Áo đấu này được làm từ 100% polyester tái chế, góp phần bảo vệ môi trường.', 'Thiết kế: Áo đấu nhà mùa 2024-2025 của Newcastle United có thiết kế truyền thống với ba sọc đen rộng rãi trên thân áo. Phông chữ \\\"Newcastle United\\\" đen rõ ràng trên lưng, cùng với biểu tượng đội bóng trên cổ tay.\\n\\nChất liệu: Áo đấu được làm từ 100% polyester tái chế, giúp bảo vệ môi trường và giảm thiểu rác thải. Chất liệu này không chỉ bền bỉ mà còn giúp thoáng khí, giữ cơ thể luôn khô ráo và thoải mái trong suốt quá trình vận động. Công nghệ HEAT.RDY tích hợp trên áo giúp loại bỏ mồ hôi nhanh chóng, đảm bảo người mặc luôn cảm thấy thoải mái và tự tin.', 65, 1),
(165, 'Áo Icon Golden State Warriors 2024', 'GSWI24', 350000, 100, 100, 'GSWI24.jpg', 'Áo đấu Golden State Warriors Icon 2024 là một phần quan trọng của dòng sản phẩm thể thao cao cấp, mang đến sự kết hợp hoàn hảo giữa thiết kế hiện đại và chất lượng cao. Thiết kế áo đấu này không chỉ thể hiện sự độc đáo và sáng tạo mà còn gắn kết với truyền thống và văn hóa của đội bóng.', 'Áo Đấu Golden State Warriors Icon 2024\\r\\nThiết kế độc đáo: Áo đấu Golden State Warriors Icon 2024 có thiết kế ấn tượng với viền màu và chữ viết \\\"Golden State\\\" trên áo và quần.\\r\\n\\r\\nChất liệu chất lượng cao: Sản phẩm được làm từ chất liệu cao cấp, mang lại độ bền cao và sự thoáng mát tối ưu.\\r\\n\\r\\nSự kết hợp với truyền thống: Thiết kế áo đấu này hòa quyện giữa phong cách hiện đại và giá trị truyền thống, gắn kết với văn hóa và lịch sử của San Francisco.\\r\\n\\r\\nSự độc đáo: Áo đấu nổi bật với viền màu đỏ cùng hình dạng cầu biểu tượng của San Francisco-Oakland Bay Bridge.', 52, 1),
(166, 'Áo Association Golden State Warriors 2024', 'GSWA24', 350000, 100, 100, 'GSWA24.jpg', 'Áo đấu Golden State Warriors Association 2024 là một phần quan trọng của dòng sản phẩm thể thao cao cấp, mang đến sự kết hợp hoàn hảo giữa thiết kế hiện đại và chất lượng cao. Thiết kế áo đấu này không chỉ thể hiện sự độc đáo và sáng tạo mà còn gắn kết với truyền thống và văn hóa của đội bóng.', 'Thiết kế độc đáo: Áo đấu Golden State Warriors Association 2024 có thiết kế độc đáo với viền màu và chữ viết bằng chữ \\\"Golden State\\\" trên áo và quần.\\n\\nChất liệu chất lượng cao: Sản phẩm được làm từ chất liệu cao cấp, đảm bảo độ bền và thoáng mát.\\n\\nSự kết hợp với truyền thống: Thiết kế áo đấu này kết hợp giữa sự hiện đại và truyền thống, gắn kết với văn hóa và lịch sử của San Francisco.\\n\\nSự độc đáo: Áo đấu có đặc điểm độc đáo với viền màu đỏ và hình dạng cầu biểu tượng của San Francisco-Oakland Bay Bridge.', 52, 1),
(167, 'Áo Icon Miami Heat 2024', 'HEAI24', 349000, 200, 200, 'HEAI24.jpg', 'Áo đấu Miami Heat Icon 2024 là một phần quan trọng của dòng sản phẩm thể thao cao cấp, mang đến sự kết hợp hoàn hảo giữa thiết kế hiện đại và chất lượng cao. Thiết kế áo đấu này không chỉ thể hiện sự độc đáo và sáng tạo mà còn gắn kết với truyền thống và văn hóa của đội bóng.', 'Thiết kế độc đáo: Áo đấu Miami Heat Icon 2024 có thiết kế độc đáo với viền màu và chữ viết bằng chữ \\\"Miami Heat\\\" trên áo và quần.\\n\\nChất liệu chất lượng cao: Sản phẩm được làm từ chất liệu cao cấp, đảm bảo độ bền và thoáng mát.\\n\\nSự kết hợp với truyền thống: Thiết kế áo đấu này kết hợp giữa sự hiện đại và truyền thống, gắn kết với văn hóa và lịch sử của Miami.\\n\\nSự độc đáo: Áo đấu có đặc điểm độc đáo với viền màu đỏ sáng và hình dạng cầu biểu tượng của Miami.', 52, 1),
(168, 'Áo Association Miami Heat 2024', 'HEAA24', 350000, 300, 300, 'HEAA24.jpg', 'Tóm tắt Áo Miami Heat Association 2024\\nMàu sắc chính: Đỏ cam\\n\\nThiết kế: Chữ và số trắng, viền đen\\n\\nChất liệu: Mềm mại, thoáng mát\\n\\nLogo và biểu tượng đặc biệt của Miami Heat', 'Áo Miami Heat Association 2024\\nMàu sắc chính: Đỏ cam (Blood Red), tượng trưng cho sự quyết tâm và sức mạnh của \\\"Heat Culture\\\".\\n\\nThiết kế đặc biệt: Áo có thiết kế độc đáo với chữ viết và số đếm trắng, được đậm hơn bởi đường viền đen.\\n\\nChất liệu: Chất liệu mềm mại, thoáng mát, rất thoải mái để mặc.\\n\\nĐặc điểm độc đáo: Áo mang logo và thiết kế đặc biệt của Miami Heat, thể hiện sự trang trọng và sự tự hào về đội.', 52, 1),
(169, 'Áo Icon Cleveland Cavaliers 2024', 'CAVI24', 350000, 100, 100, 'CAVI2024.jpg', 'Sản phẩm áo icon của Cleveland Cavaliers 2024 là một phần của dòng sản phẩm City Edition năm 2024-2025, được thiết kế để tôn vinh nền văn hóa nghệ thuật của Cleveland. Áo này được truyền cảm hứng từ Bảo tàng Nghệ thuật Cleveland và có thiết kế độc đáo với các yếu tố như màu sắc, chữ viết, và hình ảnh nghệ thuật', 'Thiết kế màu sắc và hình ảnh: Áo có các màu sắc đặc trưng và hình ảnh nghệ thuật được lấy cảm hứng từ Bảo tàng Nghệ thuật Cleveland.\\n\\nCác yếu tố độc đáo: Áo có các đoạn bên cạnh được thiết kế như một cuốn sách vẽ, với các hình ảnh và biểu tượng nổi tiếng của Cleveland.\\n\\nChất liệu và công nghệ: Áo được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.\\n\\nSứ mệnh: Áo không chỉ là một món đồ thể thao mà còn là một tác phẩm nghệ thuật, kết hợp giữa thể thao và nghệ thuật để tôn vinh di sản văn hóa và thể thao của Cleveland.', 52, 1),
(170, 'Áo Association Cleveland Cavaliers 2024', 'CAVA24', 350000, 200, 199, 'CAVA24.jpg', 'Áo Association của Cleveland Cavaliers năm 2024 là một phần trong dòng sản phẩm thường niên của NBA, được thiết kế để tôn vinh và kết nối với người hâm mộ Cleveland Cavaliers. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Cleveland Cavaliers.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Cleveland Cavaliers, cùng với logo của Nike và Cleveland-Cliffs patch.', 52, 1),
(172, 'Áo Icon Los Angeles Laker 2024', 'LALI24', 350000, 200, 199, 'LALI24.png', 'Áo Icon của Los Angeles Lakers năm 2024 là một phần của dòng sản phẩm City Edition năm 2024-2025, được thiết kế để tôn vinh và kết nối với người hâm mộ Lakers. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Các đặc điểm nổi bật của áo Icon 2024 bao gồm:\\n\\nThiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Lakers, bao gồm màu tím và vàng.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Los Angeles Lakers, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Lake Show\\\": Áo này lần đầu tiên có dòng chữ \\\"Lake Show\\\" trên áo, tôn vinh biệt danh của đội từ thời kỳ \\\"Showtime\\\".', 52, 1),
(173, 'Áo Association Los Angeles Lakers 2024', 'LALA24', 350000, 200, 200, 'LALA24.png', 'Áo Association của Los Angeles Lakers năm 2024 là một phần trong dòng sản phẩm thường niên của NBA, được thiết kế để tôn vinh và kết nối với người hâm mộ Lakers. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Lakers, bao gồm màu tím và vàng.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Los Angeles Lakers, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Lake Show\\\": Áo này lần đầu tiên có dòng chữ \\\"Lake Show\\\" trên áo, tôn vinh biệt danh của đội từ thời kỳ \\\"Showtime\\\".', 52, 1),
(174, 'Áo Icon Boston Celtics 2024', 'CELI24', 350000, 200, 200, 'CELI24.jpg', 'Áo Icon của Boston Celtics năm 2024 là một phần của dòng sản phẩm City Edition năm 2024-2025, được thiết kế để tôn vinh và kết nối với người hâm mộ Celtics. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Celtics, bao gồm màu đen và màu xanh lá cây \\\"Action Green\\\".\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Boston Celtics, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Boston Strong\\\": Áo này có dòng chữ \\\"Boston Strong\\\" trên áo, tôn vinh sức mạnh và tinh thần của đội và thành phố Boston.', 52, 1),
(175, 'Áo Association Boston Celtics 2024', 'CELA24', 350000, 300, 300, 'CELA24.jpg', 'Áo Association của Boston Celtics năm 2024 là một phần trong dòng sản phẩm thường niên của NBA, được thiết kế để tôn vinh và kết nối với người hâm mộ Celtics. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Celtics, bao gồm màu đen và màu xanh lá cây \\\"Action Green\\\".\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Boston Celtics, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Boston Strong\\\": Áo này có dòng chữ \\\"Boston Strong\\\" trên áo, tôn vinh sức mạnh và tinh thần của đội và thành phố Boston.', 52, 1),
(176, 'Áo Icon Dallas Mavericks 2024', 'MAVI24', 350000, 200, 200, 'MAVI24.jpg', 'Áo Icon của Dallas Mavericks năm 2024 là một phần của dòng sản phẩm City Edition năm 2024-2025, được thiết kế để tôn vinh và kết nối với người hâm mộ Mavericks. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Mavericks, bao gồm màu trắng và màu xanh dương.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Dallas Mavericks, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Trinity River Blues\\\": Áo này có dòng chữ \\\"Trinity River Blues\\\" trên áo, tôn vinh di sản âm nhạc Blues của Dallas/Fort Worth.', 52, 1),
(177, 'Áo Association Dallas Mavericks 2024', 'MAVA24', 350000, 200, 200, 'MAVA24.jpg', 'Áo Association của Dallas Mavericks năm 2024 là một phần trong dòng sản phẩm thường niên của NBA, được thiết kế để tôn vinh và kết nối với người hâm mộ Mavericks. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Mavericks, bao gồm màu trắng và màu xanh dương.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Dallas Mavericks, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Trinity River Blues\\\": Áo này có dòng chữ \\\"Trinity River Blues\\\" trên áo, tôn vinh di sản âm nhạc Blues của Dallas/Fort Worth.', 52, 1),
(178, 'Áo Icon Milwaukee Bucks 2024', 'BUCI24', 350000, 200, 200, 'BUCI24.jpg', 'Áo Icon của Milwaukee Bucks năm 2024 là một phần của dòng sản phẩm City Edition năm 2024-2025, được thiết kế để tôn vinh và kết nối với người hâm mộ Bucks. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Bucks, bao gồm màu xanh dương (Great Lakes Blue) và màu trắng (Cream City Cream).\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Milwaukee Bucks, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Cream City\\\": Áo này có dòng chữ \\\"Cream City\\\" trên áo, tôn vinh di sản của Milwaukee với những gạch xà phòng trắng đặc trưng.', 52, 1),
(179, 'Áo Association Milwaukee Bucks 2024', 'BUCA24', 350000, 200, 200, 'BUCA24.jpg', 'Áo Association của Milwaukee Bucks năm 2024 là một phần trong dòng sản phẩm thường niên của NBA, được thiết kế để tôn vinh và kết nối với người hâm mộ Bucks. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Bucks, bao gồm màu xanh dương (Great Lakes Blue) và màu trắng (Cream City Cream).\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Milwaukee Bucks, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Cream City\\\": Áo này có dòng chữ \\\"Cream City\\\" trên áo, tôn vinh di sản của Milwaukee với những gạch xà phòng trắng đặc trưng.', 52, 1),
(180, 'Áo Icon Houston Rocket 2024', 'HOUI24', 350000, 200, 198, 'HOUI24.png', 'Áo Icon của Houston Rockets năm 2024 là một phần của dòng sản phẩm City Edition năm 2024-2025, được thiết kế để tôn vinh và kết nối với người hâm mộ Rockets. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Các đặc điểm nổi bật của áo Icon 2024 bao gồm:\\n\\nThiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Rockets, bao gồm màu trắng và dòng chữ \\\"H-TOWN\\\" trên áo với màu đỏ và nét đen.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Houston Rockets, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Believe It Again\\\": Áo này có dòng chữ \\\"Believe It Again\\\" trên áo, tôn vinh sức mạnh và tinh thần của đội và thành phố Houston.', 52, 1),
(181, 'Áo Association Houston Rocket 2024', 'HOUA24', 350000, 200, 198, 'HOUA24.jpg', 'Áo Association của Houston Rockets năm 2024 là một phần trong dòng sản phẩm thường niên của NBA, được thiết kế để tôn vinh và kết nối với người hâm mộ Rockets. Đây là một món đồ thể thao chất lượng cao, được làm từ chất liệu Nike Dri-FIT giúp người mặc cảm thấy thoải mái và khô ráo.', 'Thiết kế đơn giản và hiện đại: Áo có thiết kế tinh tế với màu sắc đặc trưng của Rockets, bao gồm màu trắng và màu đỏ.\\n\\nChất liệu chất lượng cao: Sử dụng chất liệu Nike Dri-FIT giúp người mặc luôn cảm thấy thoải mái và khô ráo.\\n\\nLogo và số hiệu: Áo có logo và số hiệu của Houston Rockets, cùng với logo của Nike và Cleveland-Cliffs patch.\\n\\nSlogan \\\"Believe It Again\\\": Áo này có dòng chữ \\\"Believe It Again\\\" trên áo, tôn vinh sức mạnh và tinh thần của đội và thành phố Houston.', 52, 1),
(182, 'Áo Icon Chicago Bulls 2024', 'BULI24', 350000, 200, 198, 'BULI24.jpg', 'Áo Icon năm 2024 của Chicago Bulls mang đến một phong cách cổ điển, mạnh mẽ và sạch sẽ, tương tự như United Center. Thiết kế này không chỉ thể hiện sự kỷ niệm mà còn tôn vinh lịch sử và vẻ đẹp của sân nhà Bulls.', 'Thiết kế đặc biệt: Áo có màu trắng với viền và chữ \\\"Bulls\\\" trên ngực được viết bằng màu xám và viền vàng.\\n\\nHình ảnh biểu tượng: Áo có các ngôi sao đặc trưng của lá cờ Chicago trên hai bên.\\n\\nChi tiết kỷ niệm: Jock tag trên áo tôn vinh bảng viết ngoài sân United Center ghi \\\"Home of the Bulls\\\"', 52, 1),
(183, 'Áo Association Chicago Bulls 2024', 'BULA24', 250000, 300, 298, 'Bula24.jpg', 'Áo Association năm 2024 của Chicago Bulls mang đến một phong cách cổ điển, mạnh mẽ và sạch sẽ, tương tự như United Center. Thiết kế này không chỉ thể hiện sự kỷ niệm mà còn tôn vinh lịch sử và vẻ đẹp của sân nhà Bulls.', 'Thiết kế đặc biệt: Áo có màu trắng với viền và chữ \\\"Bulls\\\" trên ngực được viết bằng màu xám và viền vàng.\\n\\nHình ảnh biểu tượng: Áo có các ngôi sao đặc trưng của lá cờ Chicago trên hai bên.\\n\\nChi tiết kỷ niệm: Jock tag trên áo tôn vinh bảng viết ngoài sân United Center ghi \\\"Home of the Bulls\\\".', 52, 1),
(184, 'Áo Icon Phoenix Suns 2024', 'SUNI24', 350000, 200, 198, 'SUNI24.jpg', 'Áo Icon năm 2024 của Phoenix Suns mang đến một phong cách hiện đại, sáng tạo và truyền thống, kết hợp giữa sự kỷ niệm và phong cách mới của Suns. Thiết kế này không chỉ thể hiện sự kỷ niệm mà còn tôn vinh lịch sử và vẻ đẹp của đội bóng.', 'Thiết kế đặc biệt: Áo có màu tím với viền và chữ \\\"Suns\\\" trên ngực được viết bằng màu vàng và viền đen.\\n\\nHình ảnh biểu tượng: Áo có hình ảnh mặt trời mọc đặc trưng của Suns trên cổ tay trái.\\n\\nChi tiết kỷ niệm: Áo có số hiệu khắc trên áo và chân áo có thiết kế không đối xứng với logo \\\"Phoenix\\\" trên chân áo', 52, 1),
(185, 'Áo Association Phoenix Suns 2024', 'SUNA24', 250000, 150, 150, 'SUNA24.jpg', 'Sản phẩm áo Association của Phoenix Suns 2024 là một phần trong dòng sản phẩm đội ngũ Nike của đội bóng rổ này. Áo này có thiết kế độc đáo với biểu tượng sóng mặt trời và chữ \\\"Suns\\\" được khắc trên áo, cùng với số viền khui. Thiết kế này mang lại sự tương tác tốt với trang phục đội ngũ và mang lại cảm giác hiện đại, năng động.', 'Sản phẩm áo Association của Phoenix Suns 2024 là một phần trong dòng sản phẩm đội ngũ Nike của đội bóng rổ này. Áo này có thiết kế độc đáo với biểu tượng sóng mặt trời và chữ \\\"Suns\\\" được khắc trên áo, cùng với số viền khui. Thiết kế này mang lại sự tương tác tốt với trang phục đội ngũ và mang lại cảm giác hiện đại, năng động.\\n\\nÁo này được làm từ vải polyester tái chế, giúp giữ cho bạn mát mẻ và thoáng mát trên và ngoài sân. Ngoài ra, áo cũng có thiết kế nhẹ, tiện dụng, phù hợp để bạn có thể đeo trong suốt mùa giải.', 52, 1),
(188, 'Áo bóng chuyền nam Pro Player', 'ABC001', 350000, 100, 98, 'bc1.jpg', 'Áo bóng chuyền dành cho vận động viên chuyên nghiệp.', 'Áo bóng chuyền nam Pro Player được thiết kế đặc biệt cho các vận động viên chuyên nghiệp, mang lại hiệu suất tối đa trong mọi trận đấu. Với chất liệu cao cấp, áo đảm bảo khả năng co giãn 4 chiều, thấm hút mồ hôi hiệu quả, giữ cơ thể luôn khô thoáng và thoải mái. Đường may tỉ mỉ, họa tiết hiện đại giúp bạn tự tin cả trong và ngoài sân đấu.', 66, 1),
(189, 'Áo bóng chuyền nam Basic Fit', 'ABC002', 300000, 120, 120, 'bc2.jpg', 'Áo bóng chuyền kiểu dáng đơn giản.', 'Áo bóng chuyền nam Basic Fit là sự lựa chọn hoàn hảo cho các buổi luyện tập và trận đấu phong trào. Chất liệu cotton pha polyester giúp áo vừa mềm mại vừa bền bỉ. Thiết kế đơn giản nhưng tinh tế, dễ dàng phối hợp với các trang phục khác. Đường cắt vừa vặn giúp bạn thoải mái vận động suốt cả ngày.', 66, 1),
(190, 'Áo bóng chuyền nam CoolMax', 'ABC003', 400000, 80, 80, 'bc3.jpg', 'Áo bóng chuyền công nghệ làm mát.', 'Áo bóng chuyền CoolMax là sản phẩm cao cấp với công nghệ làm mát hiện đại. Sợi vải CoolMax giúp tăng cường luồng không khí, giảm nhiệt độ cơ thể trong khi thi đấu. Áo có thiết kế ôm sát cơ thể nhưng không gây bí bách. Đây là lựa chọn lý tưởng cho các trận đấu kéo dài hoặc trong điều kiện thời tiết nóng.', 66, 1),
(191, 'Áo bóng chuyền nam FlexMotion', 'ABC004', 450000, 90, 90, 'bc4.jpg', 'Áo bóng chuyền co giãn tối đa.', 'FlexMotion mang đến sự tự do tối đa trong mọi chuyển động. Sản phẩm sử dụng chất liệu spandex kết hợp polyester, giúp áo luôn đàn hồi mà không mất đi hình dáng ban đầu. Thiết kế năng động, đường viền cổ và tay áo gia cố chắc chắn, phù hợp với những người yêu cầu cao về hiệu suất thi đấu.', 66, 1),
(192, 'Áo bóng chuyền nam Dynamic Play', 'ABC005', 320000, 110, 110, 'bc5.jpg', 'Áo bóng chuyền dành cho mọi lứa tuổi.', 'Dynamic Play là mẫu áo dành cho mọi lứa tuổi, được yêu thích nhờ phong cách trẻ trung và năng động. Với đường may chắc chắn và chất liệu bền bỉ, áo thích hợp cho cả luyện tập và thi đấu. Họa tiết in nổi bật giúp người mặc luôn thu hút ánh nhìn trên sân.', 66, 1),
(193, 'Áo bóng chuyền nam ActiveFit', 'ABC006', 380000, 100, 100, 'bc6.jpg', 'Áo bóng chuyền nam thiết kế ôm gọn.', 'Áo ActiveFit với thiết kế ôm gọn, tôn dáng người mặc, mang lại vẻ ngoài mạnh mẽ và tự tin. Chất liệu tổng hợp cao cấp giúp áo luôn mềm mại, giảm thiểu ma sát trong quá trình vận động. Sản phẩm phù hợp cho các vận động viên yêu thích sự năng động và linh hoạt.', 66, 1),
(194, 'Áo bóng chuyền nam Thunder Strike', 'ABC007', 410000, 90, 90, 'bc7.jpg', 'Áo bóng chuyền họa tiết sấm sét.', 'Họa tiết sấm sét mạnh mẽ là điểm nhấn chính của Thunder Strike. Mẫu áo này được thiết kế cho những ai muốn thể hiện cá tính trên sân bóng. Chất liệu cao cấp giúp áo bền bỉ, không phai màu sau nhiều lần giặt. Đường cắt may khéo léo đảm bảo sự thoải mái tối đa.', 66, 1),
(195, 'Áo bóng chuyền nam EnergyBoost', 'ABC008', 390000, 95, 94, 'bc8.jpg', 'Áo bóng chuyền hỗ trợ hiệu suất tối đa.', 'EnergyBoost là mẫu áo bóng chuyền hỗ trợ tối đa cho các vận động viên muốn tăng cường hiệu suất. Công nghệ dệt vải tiên tiến giúp giảm sức cản gió, tăng độ bền và giảm mệt mỏi. Áo còn được bổ sung khả năng kháng khuẩn, giữ cơ thể luôn tươi mới.', 66, 1),
(196, 'Áo bóng chuyền nam SummerBreeze', 'ABC009', 360000, 80, 79, 'bc9.jpg', 'Áo bóng chuyền thoáng mát mùa hè.', 'Với SummerBreeze, bạn không còn phải lo lắng về cái nóng của mùa hè. Chất liệu vải siêu thoáng, nhẹ như lông vũ giúp bạn dễ dàng di chuyển. Mẫu áo này cũng phù hợp cho các hoạt động thể thao ngoài trời khác, mang lại cảm giác dễ chịu suốt cả ngày.', 66, 1),
(197, 'Áo bóng chuyền nam Storm Defender', 'ABC010', 420000, 70, 68, 'bc10.jpg', 'Áo bóng chuyền chất liệu chống thấm.', 'Storm Defender được thiết kế đặc biệt để bảo vệ cơ thể trong điều kiện ẩm ướt. Chất liệu chống thấm nước kết hợp với khả năng thoát khí tốt giúp áo luôn khô ráo. Sản phẩm phù hợp cho các vận động viên thi đấu ngoài trời.', 66, 1),
(198, 'Áo bóng chuyền nam Victory Line', 'ABC011', 350000, 100, 99, 'bc11.jpg', 'Áo bóng chuyền cho người chiến thắng.', 'Mẫu áo Victory Line được thiết kế dành riêng cho những vận động viên yêu thích sự đột phá và tinh thần chiến thắng. Đường may chắc chắn, phối màu táo bạo giúp áo luôn nổi bật trên sân. Đây là mẫu áo được nhiều đội bóng chuyên nghiệp tin dùng.', 66, 1),
(199, 'Áo bóng chuyền nam SprintFlow', 'ABC012', 340000, 120, 118, 'bc12.jpg', 'Áo bóng chuyền dành cho người yêu tốc độ.', 'SprintFlow mang đến cảm giác nhẹ nhàng và thoải mái cho các vận động viên. Công nghệ vải Aeroflow giúp tăng tốc độ di chuyển và giảm nhiệt độ cơ thể. Mẫu áo phù hợp cho các trận đấu căng thẳng yêu cầu hiệu suất cao.', 66, 1),
(200, 'Áo bóng chuyền nam Diamond Edge', 'ABC013', 450000, 75, 75, 'bc13.jpg', 'Áo bóng chuyền cao cấp với đường viền sắc nét.', 'Diamond Edge được thiết kế để tôn lên vẻ ngoài sang trọng và mạnh mẽ. Chất liệu cao cấp kết hợp với đường viền sắc nét tạo nên sự khác biệt. Áo cũng được trang bị khả năng chống mài mòn, đảm bảo độ bền lâu dài.', 66, 1),
(201, 'Áo bóng chuyền nam SwiftAir', 'ABC014', 370000, 85, 84, 'bc14.jpg', 'Áo bóng chuyền nhẹ nhàng và thoải mái.', 'SwiftAir là sự lựa chọn hoàn hảo cho những ai yêu thích sự đơn giản và thoải mái. Sản phẩm sử dụng công nghệ giảm áp lực lên cơ thể, mang lại trải nghiệm vận động nhẹ nhàng. Áo có thiết kế tối giản nhưng không kém phần hiện đại.', 66, 1),
(202, 'Áo bóng chuyền nam Limitless Motion', 'ABC015', 480000, 65, 64, 'bc15.jpg', 'Áo bóng chuyền mang lại sự tự do vận động.', 'Limitless Motion được tạo ra để mang lại sự tự do tuyệt đối trong từng chuyển động. Chất liệu cao cấp, co giãn tối đa kết hợp với thiết kế ôm sát cơ thể giúp bạn luôn đạt phong độ tốt nhất trong các trận đấu đỉnh cao.', 66, 1),
(203, 'Áo cầu lông nam Pro Smash', 'ACL001', 350000, 100, 99, 'cl1.jpg', 'Áo cầu lông dành cho vận động viên chuyên nghiệp.', 'Áo cầu lông Pro Smash được thiết kế tối ưu cho các vận động viên chuyên nghiệp. Chất liệu cao cấp giúp thấm hút mồ hôi nhanh chóng, giữ cơ thể luôn khô thoáng trong các trận đấu căng thẳng. Đường cắt may tỉ mỉ, họa tiết năng động giúp bạn luôn nổi bật trên sân.', 67, 1),
(204, 'Áo cầu lông nam FeatherLight', 'ACL002', 320000, 110, 110, 'cl2.jpg', 'Áo cầu lông siêu nhẹ, dễ vận động.', 'FeatherLight là mẫu áo cầu lông nổi bật với thiết kế siêu nhẹ, mang lại cảm giác thoải mái và linh hoạt tối đa. Chất liệu vải thoáng khí giúp giảm nhiệt độ cơ thể, giữ cho vận động viên luôn tươi mới. Thiết kế tối giản, trẻ trung, phù hợp với mọi đối tượng.', 67, 1),
(205, 'Áo cầu lông nam PowerStroke', 'ACL003', 400000, 90, 90, 'cl3.jpg', 'Áo cầu lông nam hỗ trợ sức mạnh.', 'PowerStroke mang đến sự hỗ trợ tối đa cho các vận động viên yêu thích sự mạnh mẽ. Công nghệ vải nén giúp tăng cường sức mạnh tay và giảm mệt mỏi. Mẫu áo này còn được tích hợp khả năng chống tia UV, bảo vệ da khi chơi ngoài trời.', 67, 1),
(206, 'Áo cầu lông nam AeroFlow', 'ACL004', 450000, 85, 85, 'cl4.jpg', 'Áo cầu lông nam với khả năng lưu thông khí vượt trội.', 'AeroFlow là sản phẩm được thiết kế đặc biệt để tối ưu hóa khả năng lưu thông khí. Chất liệu vải tiên tiến, nhẹ nhàng, thoáng mát giúp vận động viên tự tin trong mọi pha cầu. Đường may chắc chắn, độ bền cao là điểm cộng lớn của mẫu áo này.', 67, 1),
(207, 'Áo cầu lông nam FlexSpeed', 'ACL005', 380000, 95, 95, 'cl5.jpg', 'Áo cầu lông linh hoạt, tốc độ.', 'FlexSpeed giúp tăng tốc độ di chuyển nhờ chất liệu vải co giãn đa chiều. Thiết kế vừa vặn với đường may chắc chắn mang lại sự linh hoạt tối đa trong mọi pha cầu. Mẫu áo này thích hợp cho cả người chơi phong trào và chuyên nghiệp.', 67, 1),
(208, 'Áo cầu lông nam Victory Smash', 'ACL006', 410000, 90, 90, 'cl6.jpg', 'Áo cầu lông cho người chiến thắng.', 'Victory Smash là mẫu áo được tạo ra dành riêng cho những người yêu thích sự nổi bật. Với họa tiết táo bạo và đường may tỉ mỉ, sản phẩm giúp bạn luôn tự tin trong mọi trận đấu. Chất liệu cao cấp đảm bảo áo bền đẹp sau nhiều lần giặt.', 67, 1),
(209, 'Áo cầu lông nam SpeedMaster', 'ACL007', 340000, 100, 100, 'cl7.jpg', 'Áo cầu lông tối ưu hiệu suất.', 'SpeedMaster mang lại hiệu suất tối ưu nhờ thiết kế tinh tế và chất liệu nhẹ nhàng. Công nghệ chống bám bụi giúp áo luôn sạch sẽ sau mỗi trận đấu. Đây là lựa chọn hoàn hảo cho các vận động viên yêu thích tốc độ.', 67, 1),
(210, 'Áo cầu lông nam Lightning Strike', 'ACL008', 390000, 80, 77, 'cl8.jpg', 'Áo cầu lông họa tiết tia chớp.', 'Lightning Strike với họa tiết tia chớp là biểu tượng của sự mạnh mẽ và tốc độ. Chất liệu vải bền bỉ, thoáng khí giúp bạn luôn tự tin trên sân. Mẫu áo này thích hợp cho các trận đấu đỉnh cao.', 67, 1);
INSERT INTO `tbl_sanpham` (`id_sp`, `ten_sp`, `ma_sp`, `gia_sp`, `so_luong`, `so_luong_con_lai`, `hinh_anh`, `tom_tat`, `noi_dung`, `id_dm`, `tinh_trang`) VALUES
(211, 'Áo cầu lông nam CoolBreeze', 'ACL009', 360000, 120, 120, 'cl9.jpg', 'Áo cầu lông thoáng mát.', 'Mẫu áo CoolBreeze mang lại cảm giác thoải mái tối đa nhờ chất liệu vải thoáng khí. Đây là sản phẩm lý tưởng cho những ai thường xuyên thi đấu trong điều kiện thời tiết nóng bức. Áo còn có khả năng thấm hút mồ hôi hiệu quả, giữ cơ thể luôn khô ráo.', 67, 1),
(212, 'Áo cầu lông nam StrikeForce', 'ACL010', 420000, 75, 75, 'cl10.jpg', 'Áo cầu lông hỗ trợ động lực mạnh mẽ.', 'StrikeForce được thiết kế với đường nét mạnh mẽ, tôn lên sự năng động và cá tính của người mặc. Chất liệu chống mài mòn giúp áo bền bỉ, đồng hành cùng bạn qua mọi trận đấu khốc liệt.', 67, 1),
(213, 'Áo cầu lông nam SwiftMotion', 'ACL011', 350000, 90, 89, 'cl11.jpg', 'Áo cầu lông giúp tăng tốc độ.', 'SwiftMotion giúp bạn đạt tốc độ tối đa nhờ thiết kế ôm sát cơ thể và chất liệu vải nhẹ nhàng. Mẫu áo này mang lại cảm giác thoải mái và tự tin trong mọi pha cầu. Sản phẩm thích hợp cho các vận động viên chuyên nghiệp.', 67, 1),
(214, 'Áo cầu lông nam WindCutter', 'ACL012', 370000, 85, 85, 'cl12.jpg', 'Áo cầu lông giảm sức cản gió.', 'WindCutter được thiết kế đặc biệt để giảm sức cản gió, mang lại sự thoải mái tối đa. Với chất liệu cao cấp, mẫu áo này phù hợp với cả thi đấu và luyện tập. Thiết kế hiện đại, phối màu trẻ trung tạo nên phong cách riêng biệt.', 67, 1),
(215, 'Áo cầu lông nam BladeRunner', 'ACL013', 390000, 100, 96, 'cl13.jpg', 'Áo cầu lông bền bỉ và sắc sảo.', 'BladeRunner là mẫu áo được thiết kế cho những người yêu thích sự mạnh mẽ. Chất liệu vải bền bỉ, đường may chắc chắn giúp áo giữ nguyên dáng sau nhiều lần giặt. Mẫu áo này mang lại sự thoải mái và tự tin trong suốt trận đấu.', 67, 1),
(216, 'Áo cầu lông nam AeroStrike', 'ACL014', 410000, 110, 110, 'cl14.jpg', 'Áo cầu lông với khả năng làm mát tuyệt vời.', 'AeroStrike sử dụng công nghệ làm mát tiên tiến, mang lại sự thoải mái và nhẹ nhàng trong từng chuyển động. Sản phẩm còn được tích hợp khả năng chống mùi, giúp bạn tự tin thi đấu cả ngày.', 67, 1),
(217, 'Áo cầu lông nam Supreme Control', 'ACL015', 450000, 70, 70, 'cl15.jpg', 'Áo cầu lông kiểm soát tối ưu.', 'Supreme Control mang lại khả năng kiểm soát tối ưu trong mọi pha cầu. Với chất liệu co giãn 4 chiều, áo giúp vận động viên dễ dàng thực hiện các động tác kỹ thuật khó. Đây là lựa chọn hoàn hảo cho những ai yêu thích sự chính xác và hiệu suất.', 67, 1),
(218, 'Áo cầu lông nam SpeedFlex', 'ACL016', 360000, 100, 92, 'cl16.jpg', 'Áo cầu lông nhanh chóng, linh hoạt.', 'SpeedFlex được thiết kế cho những ai yêu thích sự linh hoạt và tốc độ. Với chất liệu nhẹ và co giãn, áo giúp bạn di chuyển dễ dàng trong mọi trận đấu. Thiết kế thể thao, trẻ trung phù hợp với nhiều đối tượng vận động viên.', 67, 1),
(219, 'Áo cầu lông nam TurboSpeed', 'ACL017', 380000, 95, 92, 'cl17.jpg', 'Áo cầu lông sở hữu siêu tốc độ.', 'TurboSpeed mang đến cảm giác tốc độ tuyệt vời nhờ thiết kế ôm sát và chất liệu vải siêu nhẹ. Áo giúp bạn đạt được tốc độ tối đa trong mọi chuyển động. Dễ dàng giặt sạch và giữ màu sắc lâu dài.', 67, 1),
(220, 'Áo cầu lông nam UltraStrike', 'ACL018', 420000, 85, 75, 'cl18.jpg', 'Áo cầu lông cho chiến thuật tấn công.', 'UltraStrike là sự lựa chọn tuyệt vời cho những vận động viên yêu thích lối chơi tấn công. Chất liệu vải giúp thấm hút mồ hôi hiệu quả, giữ cơ thể khô ráo và thoải mái suốt trận đấu. Họa tiết mạnh mẽ, phù hợp với những pha tấn công quyết đoán.', 67, 1),
(221, 'Áo cầu lông nam PowerFlex', 'ACL019', 400000, 90, 36, 'cl19.jpg', 'Áo cầu lông với sự kết hợp giữa sức mạnh và linh hoạt.', 'PowerFlex được thiết kế đặc biệt với chất liệu co giãn giúp bạn dễ dàng thực hiện mọi động tác mà không lo hạn chế. Đường may chắc chắn, đồng thời hỗ trợ tối đa các vận động viên trong những pha cầu mạnh mẽ.', 67, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_sanpham`
--
ALTER TABLE `tbl_sanpham`
  ADD PRIMARY KEY (`id_sp`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_sanpham`
--
ALTER TABLE `tbl_sanpham`
  MODIFY `id_sp` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=226;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
